# Generated by Django 4.1.1 on 2022-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_desciption_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
