# Generated by Django 4.1.1 on 2022-10-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisementpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementpage',
            name='body',
        ),
        migrations.AddField(
            model_name='advertisementpage',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisementpage',
            name='how_to_donate',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
